### ISSUE TITLE
valid_mask设置

### ISSUE THREAD

**Issue by lwx19880330** [zheng-yuwei/multi-label-classification#6]
作者你好  我在测试GHM  使用的时候 valid_mask 参数怎么设置啊

**Comment by zheng-yuwei** [comment]
> 作者你好 我在测试GHM 使用的时候 valid_mask 参数怎么设置啊

可以参考 [valid_mask = 1.0 - tf.cast(tf.less(y_truth, 0), dtype=tf.float32)](https://github.com/zheng-yuwei/multi-label-classification/blob/3563628060e5a9534b106414a193e71c2fa001b8/multi_label/multi_label_loss.py#L140)，这个参数是作为哪些样本是需要统计loss的标志位，所以你可以直接按上面等式这样设置

**Comment by qiaoxiu** [comment]
非常感谢你的回复，我这还有一个问题 不知道 是不是 我操作的问题 
y_truth = keras.backend.flatten(y_truth)    针对y_truth进行平铺  
然后进行 y_truth = keras.backend.one_hot(indices=y_truth, num_classes=2)
会导致 后面 y_pred和y_truth  的 shape  不匹配

**Comment by zheng-yuwei** [comment]
> 非常感谢你的回复，我这还有一个问题 不知道 是不是 我操作的问题
> y_truth = keras.backend.flatten(y_truth) 针对y_truth进行平铺
> 然后进行 y_truth = keras.backend.one_hot(indices=y_truth, num_classes=2)
> 会导致 后面 y_pred和y_truth 的 shape 不匹配

你这样我也不知道什么问题呀 -。- 要不你自己debug看看

**Comment by qiaoxiu** [comment]
好了 非常感谢

**Comment by zheng-yuwei** [comment]
> 好了 非常感谢

good~

**Comment by wangcc440** [comment]
作者你好，运行ghm时报错
valid_bin = tf.reduce_sum(tf.cast(valid_bin, dtype=tf.float32), axis=(1, 2))
这行代码的axis与valid_bin的shape(30, None)不匹配
报错：ValueError: Invalid reduction dimension 2 for input with 2 dimensions. for '{{node ghm_class_loss/Sum}} = Sum[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=false](ghm_class_loss/Cast_2, ghm_class_loss/Sum/reduction_indices)' with input shapes: [30,?], [2] and with computed input tensors: input[1] = <1 2>.

请问要怎么解决维度问题，非常感谢。

**Comment by cfjcyc0301** [comment]
> > 好了 非常感谢
> 
> good~

作者你好，运行ghm时报错

`valid_bin = tf.reduce_sum(tf.cast(valid_bin, dtype=tf.float32), axis=(1, 2))`
这行代码的`axis=(1, 2)`与valid_bin的shape(30, None)不匹配

报错：ValueError: Invalid reduction dimension 2 for input with 2 dimensions. for '{{node ghm_class_loss/Sum}} = Sum[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=false](ghm_class_loss/Cast_2, ghm_class_loss/Sum/reduction_indices)' with input shapes: [30,?], [2] and with computed input tensors: input[1] = <1 2>.

我最近一直在改ghm代码，但都是报错，请问要怎么解决维度问题，希望作者能回复我，非常感谢。

**Comment by zheng-yuwei** [comment]
没遇到过，我也不太清楚。可能需要你自己debug一下了... 这个库是2年前的了，我已经转投pytorch了 : )
